variable "rg" {}
variable "region" {}
variable "server_name" {}
variable "database_sku" {} 
variable "database_name" {}
variable "database_storage" {}
variable "backup_days" {} 
variable "geo_redundant" {}  
variable "database_username" {}  
variable "database_version" {} 
variable "db_ssl_enforcement" {} 
variable "auto_grow" {} 
variable "priv_endpoint_name" {}
variable "vnet_name" {}
variable "vnet_rg_name" {}
variable "subnet_name" {}
variable "bill_indicator_tag" {}
variable "company_code_tag" {}  
variable "env_tag" {}           
variable "consumer_org1_tag" {}
variable "consumer_org2_tag" {} 
variable "support_stat_tag" {}  